name: QDomyos-Zwift
version: "nightly-2026-05-07"
slug: qdomyos_zwift
description: >-
  Runs qdomyos-zwift (by cagnulein) as a Home Assistant add-on. Access the web interface on the configured port (default: 8080).
url: https://github.com/sondregronas/hass-apps/tree/main/qdomyos_zwift
arch:
  - amd64
init: false
privileged:
  - NET_ADMIN
host_network: true
image: ghcr.io/sondregronas/qdomyos-zwift-addon
map:
  - addon_config:rw
host_dbus: true
usb: true
uart: true
options:
  port: 8080
  log_level: info
  no_gui: false
schema:
  port: int
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  no_gui: bool
