name: QDomyos-Zwift
version: "nightly-2026-05-06"
slug: qdomyos_zwift
description: >-
  Dockerfile wrapper for qdomyos-zwift by cagnulein.
  
  Visit the application the specified port on the host machine to access the web interface. (Default port: 8080)
url: https://github.com/sondregronas/hass-apps/tree/main/qdomyos_zwift
arch:
  - amd64
init: false
privileged:
  - NET_ADMIN
host_network: true
image: ghcr.io/sondregronas/qdomyos-zwift-addon
map:
  - addon_config:rw
host_dbus: true
usb: true
uart: true
options:
  port: 8080
  log_level: info
schema:
  port: int
  log_level: list(trace|debug|info|notice|warning|error|fatal)
