services:
  qdomyos-zwift:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./qz_config:/config
    environment:
      - NO_GUI=false
    restart: unless-stopped
